services:

  # ----------------------------------------------------------------------------
  # Talaria Lab Target Container
  # ----------------------------------------------------------------------------
  talaria-lab:
    build:
      context: .
      dockerfile: Dockerfile.lab
    container_name: talaria-lab-target
    hostname: talaria-lab
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    volumes:
      # Optional volume mount to output scan report to host directory
      - ./lab_reports:/home/tester/reports
    command: /bin/bash
